---
title: "p8105_hw6_yz4993"
author: "Yixin Zheng"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnoaa)
library(broom)
```

# Problem 1
```{r download and preprocess data}
weather_df <- rnoaa::meteo_pull_monitors(
  c("USW00094728"),
  var = c("PRCP", "TMIN", "TMAX"), 
  date_min = "2017-01-01",
  date_max = "2017-12-31"
) %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10
  ) %>%
  select(name, id, everything())
```

```{r bootstrap}
# define function
bootstrap_sample <- function(df) {
  sample_frac(df, replace = TRUE)
}

# bootstrapping, 5000 samples with replacement
results_p1 <- 
  tibble(bootstrap_id = 1:5000) %>%
  mutate(
    bootstrap_sample = map(bootstrap_id, ~ bootstrap_sample(weather_df)),
    bootstrap_model = map(bootstrap_sample, ~ lm(tmax ~ tmin, data = .x)),
    # extract r-squared and compute log(beta0 * beta1)
    r_squared = map_dbl(bootstrap_model, ~ glance(.x)$r.squared),
    log_beta = map_dbl(bootstrap_model, ~ {
      coefs <- tidy(.x)
      log(coefs$estimate[1] * coefs$estimate[2])
    })
  )

# 95% confidence intervals
ci_r_squared <- results_p1 %>% 
  summarize(ci_low = quantile(r_squared, 0.025), 
            ci_high = quantile(r_squared, 0.975))

ci_log_beta <- results_p1 %>% 
  summarize(ci_low = quantile(log_beta, 0.025), 
            ci_high = quantile(log_beta, 0.975))

ci_r_squared %>% 
  mutate(parameter = "R-squared") %>%
  bind_rows(ci_log_beta %>% mutate(parameter = "log(beta_hat_0 * beta_hat_1)")) %>%
  select(parameter, ci_low, ci_high) %>%
  knitr::kable(digits = 3, col.names = c("Parameter", "2.5% Quantile", "97.5% Quantile"))

# plot distributions
r_squared_plot <- 
  results_p1 %>%
  ggplot(aes(x = r_squared)) +
  geom_histogram(binwidth = 0.01, fill = "pink", alpha = 0.7) +
  labs(
    title = "Distribution of R-squared",
    x = "R-squared",
    y = "Frequency"
  )

log_beta_plot <- 
  results_p1 %>%
  ggplot(aes(x = log_beta)) +
  geom_histogram(binwidth = 0.1, fill = "gold", alpha = 0.7) +
  labs(
    title = "Distribution of log(beta_hat_0 * beta_hat_1)",
    x = "log(beta_hat_0 * beta_hat_1)",
    y = "Frequency"
  )

r_squared_plot
log_beta_plot
```

# Problem 2
```{r data import and clean}
homicide_data <- read_csv("~/Desktop/Data Science/HW/HW6/p8105_hw6_yz4993/data/homicide-data.csv") %>%
  janitor::clean_names() %>%
  mutate(city_state = str_c(city, state, sep = ", "),
         resolved_case = if_else(disposition == "Closed by arrest", 1, 0),
         victim_age = as.numeric(victim_age)) %>%
  filter(!city_state %in% c("Dallas, TX", 
                            "Phoenix, AZ", 
                            "Kansas City, MO", 
                            "Tulsa, AL")) %>%
  filter(victim_race %in% c("White", "Black")) %>%
  drop_na(victim_race, victim_sex, victim_age)
```